#include <emscripten/bind.h>
#include "../../vendor/FastNoise.h"

EMSCRIPTEN_BINDINGS(FastNoise) {
  class_<FastNoise>("FastNoiseEm")
    .constructor<int>()
    .function("SetSeed", &FastNoise.SetSeed)
    .function("GetSeed", &FastNoise.GetSeed)
    .function("SetFrequency", &FastNoise.SetFrequency)
    .function("GetFrequency", &FastNoise.GetFrequency)
    .function("SetInterp", &FastNoise.SetInterp)
    .function("GetInterp", &FastNoise.GetInterp)
    .function("SetNoiseType", &FastNoise.SetNoiseType)
    .function("GetNoiseType", &FastNoise.GetNoiseType)
    .function("SetFractalOctaves", &FastNoise.SetFractalOctaves)
    .function("GetFractalOctaves", &FastNoise.GetFractalOctaves)
    .function("SetFractalLacunarity", &FastNoise.SetFractalLacunarity)
    .function("GetFractalLacunarity", &FastNoise.GetFractalLacunarity)
    .function("SetFractalGain", &FastNoise.SetFractalGain)
    .function("GetFractalGain", &FastNoise.GetFractalGain)
    .function("SetFractalType", &FastNoise.SetFractalType)
    .function("GetFractalType", &FastNoise.GetFractalType)
    .function("SetCellularDistanceFunction", &FastNoise.SetCellularDistanceFunction)
    .function("GetCellularDistanceFunction", &FastNoise.GetCellularDistanceFunction)
    .function("SetCellularReturnType", &FastNoise.SetCellularReturnType)
    .function("GetCellularReturnType", &FastNoise.GetCellularReturnType)
    .function("SetCellularNoiseLookup", &FastNoise.SetCellularNoiseLookup)
    .function("GetCellularNoiseLookup", &FastNoise.GetCellularNoiseLookup)
    .function("SetCellularDistance2Indices", &FastNoise.SetCellularDistance2Indices)
    .function("GetCellularDistance2Indices", &FastNoise.GetCellularDistance2Indices)
    .function("SetCellularJitter", &FastNoise.GetCellularDistance2Indices)
    .function("GetCellularJitter", &FastNoise.GetCellularJitter)
    .function("SetGradientPerturbAmp", &FastNoise.SetGradientPerturbAmp)
    .function("GetGradientPerturbAmp", &FastNoise.GetGradientPerturbAmp)

    // all the following are overloaded for 2D, 3D, and 4D
    // so same function names can be used
    .function("GetValue", &FastNoise.GetValue)
    .function("GetValueFractal", &FastNoise.GetValueFractal)
    .function("GetPerlin", &FastNoise.GetPerlin)
    .function("GetPerlinFractal", &FastNoise.GetPerlinFractal)
    .function("GetSimplex", &FastNoise.GetSimplex)
    .function("GetSimplexFractal", &FastNoise.GetSimplexFractal)
    .function("GetCellular", &FastNoise.GetCellular)
    .function("GetWhiteNoise", &FastNoise.GetWhiteNoise)
    .function("GetWhiteNoiseInt", &FastNoise.GetWhiteNoiseInt)
    .function("GetCubic", &FastNoise.GetCubic)
    .function("GetCubicFractal", &FastNoise.GetCubicFractal)
    .function("GetNoise", &FastNoise.GetNoise)
    .function("GradientPerturb", &FastNoise.GradientPerturb)
    .function("GradientPerturbFractal", &FastNoise.GetNoise)
    .function("GetSimplex", &FastNoise.GetSimplex)
    .function("GetWhiteNoise", &FastNoise.GetWhiteNoise)
    .function("GetWhiteNoiseInt", &FastNoise.GetWhiteNoiseInt)
    ;
}
